# Generated by Django 4.0.6 on 2022-07-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
